<a href="https://colab.research.google.com/github/Arshnoor7/Machine_Learning/blob/main/ML_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas Introduction**

In [67]:
import pandas as pd
df=pd.DataFrame()
df['Name']=['Arsh','Adak','Mona','Manish','Nirnaya','Sudeep','Nitesh','Ashutosh','Vishakha','Satakshi']
df['Gender']=['F','M','F','M','M','M','M','M','F','F']
df['Age']=[18,18,20,19,20,21,21,20,21,20]
print(df)
df.to_csv('Data.csv',index=False)

       Name Gender  Age
0      Arsh      F   18
1      Adak      M   18
2      Mona      F   20
3    Manish      M   19
4   Nirnaya      M   20
5    Sudeep      M   21
6    Nitesh      M   21
7  Ashutosh      M   20
8  Vishakha      F   21
9  Satakshi      F   20

In [68]:
df=pd.read_csv('Data.csv')
df

       Name Gender  Age
0      Arsh      F   18
1      Adak      M   18
2      Mona      F   20
3    Manish      M   19
4   Nirnaya      M   20
5    Sudeep      M   21
6    Nitesh      M   21
7  Ashutosh      M   20
8  Vishakha      F   21
9  Satakshi      F   20

In [69]:
df.iloc[2]

Name      Mona
Gender       F
Age         20
Name: 2, dtype: object

In [70]:
df.iloc[1:]

       Name Gender  Age
1      Adak      M   18
2      Mona      F   20
3    Manish      M   19
4   Nirnaya      M   20
5    Sudeep      M   21
6    Nitesh      M   21
7  Ashutosh      M   20
8  Vishakha      F   21
9  Satakshi      F   20

In [71]:
df.iloc[1:,0:1]

       Name
1      Adak
2      Mona
3    Manish
4   Nirnaya
5    Sudeep
6    Nitesh
7  Ashutosh
8  Vishakha
9  Satakshi

In [72]:
df['Gender']=='F'

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8     True
9     True
Name: Gender, dtype: bool

In [73]:
df[df['Gender']=='F']

       Name Gender  Age
0      Arsh      F   18
2      Mona      F   20
8  Vishakha      F   21
9  Satakshi      F   20

In [74]:
df[df['Age']>18]

       Name Gender  Age
2      Mona      F   20
3    Manish      M   19
4   Nirnaya      M   20
5    Sudeep      M   21
6    Nitesh      M   21
7  Ashutosh      M   20
8  Vishakha      F   21
9  Satakshi      F   20

In [75]:
df[(df['Age'] > 19) | (df['Gender'] == 'F')]

       Name Gender  Age
0      Arsh      F   18
2      Mona      F   20
4   Nirnaya      M   20
5    Sudeep      M   21
6    Nitesh      M   21
7  Ashutosh      M   20
8  Vishakha      F   21
9  Satakshi      F   20

In [76]:
df[(df['Age'] > 19) & (df['Gender'] == 'F')]

       Name Gender  Age
2      Mona      F   20
8  Vishakha      F   21
9  Satakshi      F   20

# **Dataset**

In [77]:
from google.colab import files
uploaded = files.upload()

Saving AWCustomers.csv to AWCustomers (1).csv
Saving AWSales.csv to AWSales (1).csv

In [78]:
df=pd.read_csv('AWCustomers.csv')
df

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,NaN,Grace,C,Bailey,NaN,6627 Camelback Ct.,NaN,Coronado,California,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,NaN,Tasha,NaN,Deng,NaN,9627 Kendall Rd,NaN,Port Macquarie,New South Wales,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,NaN,Jaclyn,NaN,Zhang,NaN,4364 Viera Avenue,NaN,Beaverton,Oregon,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,NaN,Erin,I,Reed,NaN,3866 Mt. Everest Court,NaN,Vancouver,British Columbia,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06
18360,16676,NaN,Amanda,NaN,Perry,NaN,7870 Orangewood Dr.,NaN,Grossmont,California,...,Graduate Degree,Professional,F,M,1,2,0,0,136856,2017-03-06

In [79]:
df.columns

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [80]:
df['Title'].unique()

array([nan, 'Ms.', 'Mrs.', 'Mr.', 'Sr.', 'Ms'], dtype=object)

In [81]:
df['Suffix'].unique()

array([nan, 'Jr.'], dtype=object)

In [82]:
data=df[['CustomerID','PostalCode','BirthDate','Education','Occupation','Gender','MaritalStatus','HomeOwnerFlag','NumberCarsOwned','NumberChildrenAtHome','TotalChildren','YearlyIncome']]

In [83]:
sale=pd.read_csv('AWSales.csv')
sale

       CustomerID  BikeBuyer  AvgMonthSpend
0           21173          1          50.97
1           13249          1          53.11
2           29350          1          54.08
3           13503          1          56.93
4           22803          1          55.41
...           ...        ...            ...
18350       25414          0          48.14
18351       11459          1          50.23
18352       12160          1          49.56
18353       14353          0          51.42
18354       16676          1          52.27

[18355 rows x 3 columns]

In [84]:
data=pd.merge(data,sale,on='CustomerID')

In [85]:
data

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,21173,2500,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916,1,50.97
1,13249,V9B 2C3,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076,1,53.11
2,29350,91791,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387,1,54.08
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481,1,56.93
4,22803,59368,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804,1,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,0,48.14
18357,11459,2444,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,1,50.23
18358,12160,97005,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,51859,1,49.56
18359,14353,V7L 4J4,1995-06-15,High School,Clerical,F,S,0,0,0,0,87177,0,51.42
18360,16676,91941,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,136856,1,52.27

**Determine a Data value type (Discrete, or Continuous, then Nominal, Ordinal, Interval, Ratio) of
each attribute in your selection to identify preprocessing tasks to create input for your data mining.**


1. CustomerID: Discrete, Nominal
2. PostalCode: Discrete, Nominal
3. BirthDate: Continuous, Interval
4. Education: Discrete, Ordinal
5. Occupation: Discrete, Nominal
6. Gender: Discrete, Nominal
7. MaritalStatus: Discrete, Nominal
8. HomeOwnerFlag: Discrete, Nominal
9. NumberCarsOwned: Discrete, Ratio
10. NumberChildrenAtHome: Discrete, Ratio
11. TotalChildren: Discrete, Ratio
12. YearlyIncome: Continuous, Ratio
13. BikeBuyer: Discrete, Nominal
14. AvgMonthSpend: Continuous, Ratio

# **Part II: Data Preprocessing and Transformation**
Depending on the data type of each attribute, transform each object from your preprocessed data.

Use all the data rows (~= 18000 rows) with the selected features as input to apply all the tasks below, do
not perform each task on the smaller data set that you got from your random sampling result.

(a) Handling Null values

(b) Normalization

(c) Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different
values

(d) Standardization/Normalization

(e) Binarization (One Hot Encoding)

# **Handling Null Values**

In [86]:
data.isnull().sum()

CustomerID              0
PostalCode              0
BirthDate               0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
BikeBuyer               0
AvgMonthSpend           0
dtype: int64

In [87]:
# add Null value to data
import numpy as np

data.loc[3,'Gender']=np.nan

In [88]:
data.loc[18359,'YearlyIncome']=np.nan

In [89]:
data

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,21173,2500,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916.0,1,50.97
1,13249,V9B 2C3,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076.0,1,53.11
2,29350,91791,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387.0,1,54.08
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,NaN,M,1,2,1,2,61481.0,1,56.93
4,22803,59368,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804.0,1,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953.0,0,48.14
18357,11459,2444,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,60992.0,1,50.23
18358,12160,97005,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,51859.0,1,49.56
18359,14353,V7L 4J4,1995-06-15,High School,Clerical,F,S,0,0,0,0,NaN,0,51.42
18360,16676,91941,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,136856.0,1,52.27

In [90]:
data.isnull().sum()

CustomerID              0
PostalCode              0
BirthDate               0
Education               0
Occupation              0
Gender                  1
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            1
BikeBuyer               0
AvgMonthSpend           0
dtype: int64

In [91]:
data[data['Gender'].isna()]

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,NaN,M,1,2,1,2,61481.0,1,56.93

In [92]:
mode_val=data['Gender'].mode()[0]
data['Gender'].fillna(mode_val,inplace=True)

In [93]:
data

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,21173,2500,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916.0,1,50.97
1,13249,V9B 2C3,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076.0,1,53.11
2,29350,91791,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387.0,1,54.08
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481.0,1,56.93
4,22803,59368,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804.0,1,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953.0,0,48.14
18357,11459,2444,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,60992.0,1,50.23
18358,12160,97005,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,51859.0,1,49.56
18359,14353,V7L 4J4,1995-06-15,High School,Clerical,F,S,0,0,0,0,NaN,0,51.42
18360,16676,91941,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,136856.0,1,52.27

In [94]:
data['YearlyIncome'].fillna(data['YearlyIncome'].mean(),inplace=True)

In [95]:
data

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,21173,2500,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916.000000,1,50.97
1,13249,V9B 2C3,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076.000000,1,53.11
2,29350,91791,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387.000000,1,54.08
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481.000000,1,56.93
4,22803,59368,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804.000000,1,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953.000000,0,48.14
18357,11459,2444,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,60992.000000,1,50.23
18358,12160,97005,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,51859.000000,1,49.56
18359,14353,V7L 4J4,1995-06-15,High School,Clerical,F,S,0,0,0,0,72753.994118,0,51.42
18360,16676,91941,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,136856.000000,1,52.27

# **Normalisation (MinMaxScaler)**

In [96]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
data['YearlyIncome']=scaler.fit_transform(data[['YearlyIncome']])

In [97]:
data

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,21173,2500,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,0.496842,1,50.97
1,13249,V9B 2C3,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,0.489453,1,53.11
2,29350,91791,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,0.536172,1,54.08
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,0.317083,1,56.93
4,22803,59368,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,0.231958,1,55.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,0.242065,0,48.14
18357,11459,2444,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,0.312781,1,50.23
18358,12160,97005,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,0.232442,1,49.56
18359,14353,V7L 4J4,1995-06-15,High School,Clerical,F,S,0,0,0,0,0.416247,0,51.42
18360,16676,91941,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,0.980128,1,52.27

In [98]:
data['AvgMonthSpend']=scaler.fit_transform(data[['AvgMonthSpend']])

In [99]:
data

,CustomerID,PostalCode,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,21173,2500,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,0.496842,1,0.324210
1,13249,V9B 2C3,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,0.489453,1,0.425201
2,29350,91791,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,0.536172,1,0.470977
3,13503,L4 4HB,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,0.317083,1,0.605474
4,22803,59368,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,0.231958,1,0.533742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,0.242065,0,0.190656
18357,11459,2444,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,0.312781,1,0.289287
18358,12160,97005,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,0.232442,1,0.257669
18359,14353,V7L 4J4,1995-06-15,High School,Clerical,F,S,0,0,0,0,0.416247,0,0.345446
18360,16676,91941,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,0.980128,1,0.385559

# **Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different values**

In [100]:
'''import pandas as pd
import numpy as np
bins=np.linspace(min(data['YearlyIncome']),max(data['YearlyIncome']),4)
group_names=['Poor','Average','Rich']
data['YearlyIncome']=pd.cut(data['YearlyIncome'],bins,group_names,include_lowest=True)'''

"import pandas as pd\nimport numpy as np\nbins=np.linspace(min(data['YearlyIncome']),max(data['YearlyIncome']),4)\ngroup_names=['Poor','Average','Rich']\ndata['YearlyIncome']=pd.cut(data['YearlyIncome'],bins,group_names,include_lowest=True)"

In [101]:
# Discretization (Binning) of Continuous Attributes
from sklearn.preprocessing import KBinsDiscretizer
binner = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='uniform')
col_to_bin = ['YearlyIncome']
df_binned = pd.DataFrame(binner.fit_transform(data[col_to_bin]), columns=col_to_bin)
#df_binned = pd.DataFrame(binner.fit_transform(col_to_bin), columns=col_to_bin.columns)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(

In [102]:
df_binned

       YearlyIncome
0               2.0
1               2.0
2               2.0
3               1.0
4               1.0
...             ...
18356           1.0
18357           1.0
18358           1.0
18359           2.0
18360           4.0

[18361 rows x 1 columns]

# **Binarization (One Hot Encoding)**

In [103]:
from sklearn.preprocessing import OneHotEncoder
categorical_columns = ['Education',	'Occupation',	'Gender',	'MaritalStatus'	]

encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(data[categorical_columns])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))


df_encoded = pd.concat([data, one_hot_df], axis=1)


df_encoded = df_encoded.drop(categorical_columns, axis=1)

In [104]:
df_encoded

,CustomerID,PostalCode,BirthDate,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend,...,Education_Partial High School,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual,Gender_F,Gender_M,MaritalStatus_M,MaritalStatus_S
0,21173,2500,1987-11-13,1,3,0,1,0.496842,1,0.324210,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,13249,V9B 2C3,1972-07-21,1,2,1,2,0.489453,1,0.425201,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,29350,91791,1985-11-09,0,3,0,0,0.536172,1,0.470977,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,13503,L4 4HB,1977-10-18,1,2,1,2,0.317083,1,0.605474,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,22803,59368,1975-02-05,1,1,0,0,0.231958,1,0.533742,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,92118,1990-11-11,0,1,0,2,0.242065,0,0.190656,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
18357,11459,2444,1992-10-13,0,2,0,0,0.312781,1,0.289287,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
18358,12160,97005,1983-11-24,0,2,0,0,0.232442,1,0.257669,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
18359,14353,V7L 4J4,1995-06-15,0,0,0,0,0.416247,0,0.345446,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
18360,16676,91941,1986-03-26,1,2,0,0,0.980128,1,0.385559,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

# **Standardization**

In [105]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
col = ['YearlyIncome']
df_standardized = pd.DataFrame(scaler.fit_transform(data[col]), columns=col)

In [106]:
df_standardized

       YearlyIncome
0      2.985826e-01
1      2.712077e-01
2      4.442890e-01
3     -3.673781e-01
4     -6.827440e-01
...             ...
18356 -6.452989e-01
18357 -3.833142e-01
18358 -6.809515e-01
18359  4.113090e-16
18360  2.089034e+00

[18361 rows x 1 columns]

Part III: Calculating Proximity /Correlation Analysis of two features
Make sure each attribute is transformed in a same scale for numeric attributes and Binarization for each
nominal attribute, and each discretized numeric attribute to standardization. Make sure to apply a correct
similarity measure for nominal (one hot encoding)/binary attributes and numeric attributes respectively.

(a) Calculate Similarity in Simple Matching, Jaccard Similarity, and Cosine Similarity between two
following objects of your transformed input data.

(b) Calculate Correlation between two features Commute Distance and Yearly Income

In [107]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import jaccard
import numpy as np

# Load the data

df = data.copy()  # Create a copy of the original DataFrame

# Select numeric and categorical columns
numeric_cols = ['YearlyIncome', 'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'AvgMonthSpend']
categorical_cols = ['Education', 'Occupation', 'MaritalStatus', 'Gender', 'HomeOwnerFlag']

# Step 1: Standardize numeric attributes
scaler = StandardScaler()
numeric_data = scaler.fit_transform(df[numeric_cols])

# Step 2: Binarize categorical attributes (One-Hot Encoding)
encoder = OneHotEncoder(sparse_output=False)
categorical_data = encoder.fit_transform(df[categorical_cols])

# Combine the processed data
processed_data = np.hstack([numeric_data, categorical_data])

# Convert processed data back to a DataFrame for easier handling
processed_df = pd.DataFrame(processed_data)

# Step 3: Calculate Similarity between two objects (first two rows as an example)
obj1 = processed_df.iloc[0].values
obj2 = processed_df.iloc[1].values

# Simple Matching Coefficient (SMC)
def simple_matching_coefficient(a, b):
    return sum(a == b) / len(a)

smc = simple_matching_coefficient(obj1, obj2)
print("Simple Matching Coefficient:", smc)

# Jaccard Similarity
def jaccard_similarity(a, b):
    return 1 - jaccard(a, b)

jacc_sim = jaccard_similarity(obj1, obj2)
print("Jaccard Similarity:", jacc_sim)

# Cosine Similarity
cos_sim = cosine_similarity([obj1], [obj2])[0][0]
print("Cosine Similarity:", cos_sim)

# Step 4: Calculate Correlation between `AvgMonthSpend` and `YearlyIncome`
correlation = df['AvgMonthSpend'].corr(df['YearlyIncome'])
print("Correlation between AvgMonthSpend and YearlyIncome:", correlation)

Simple Matching Coefficient: 0.6666666666666666
Jaccard Similarity: 0.36363636363636365
Cosine Similarity: 0.5612086427683285
Correlation between AvgMonthSpend and YearlyIncome: 0.5301314869870086